# This workflow performs unit testing on the utility package
name: Unit Testing

on:
  pull_request:
    paths: 
      - 'utils/**'
      - 'go.*'
      - '.github/workflows/unit-testing.yml'
  # manual trigger
  workflow_dispatch:

jobs:
  test-utils:
    name: Test Utils
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.*

    - run: go test ./utils -count=100
